### PR TITLE
Make FILE capture option during compilation and run time

### PR DESCRIPTION
**Pull request by Thecarisma**

### CODE REVIEW

**Comment by Thecarisma** [comment]
Apply an update to make the default output format text to allow the text in `CESTER_COMMENT `to be printed out. Should resolve issue https://github.com/exoticlibraries/libcester/issues/66

**Comment by chenyulue** [comment]
As for #66 , you have made the following changes:

```c
if (superTestInstance.output_format == CESTER_NULL) {
        superTestInstance.output_format = (char*) malloc(sizeof(char) * 5);
        superTestInstance.output_format[0] = 't';
        superTestInstance.output_format[1] = 'e';
        superTestInstance.output_format[2] = 'x';
        superTestInstance.output_format[3] = 't';
        superTestInstance.output_format[4] = '\n';
    }
```

Should the last line `superTestInstance.output_format[4]`  be `'\0'`?

For learning purpose, I wonder why not `if (superTestInstance.output_format == CESTER_NULL) superTestInstance.output_format = (char*)"text";`?

**Comment by Thecarisma** [comment]
Omg 😱 , it should be '\0'.

I use malloc to allocate the string because in the macros that changes
output format, like CESTER_OUTPUT_FORMAT_JUNITXML(), I
free superTestInstance.output_format before changing the value, so if I do
direct assignment the macros will cause segfault

**Comment by Thecarisma** [comment]
@chenyulue I just merge https://github.com/exoticlibraries/libcester/pull/68 which fix the output format missing `\0` bug and also update it to store the output format on the stack instead of HEAP

**Comment by chenyulue** [comment]
Awesome!^v^

**Pull request merged**
