### PR TITLE
Do not copy FILE objects

### PR DESCRIPTION
**Pull request by Inkrementator**
Fixes error in Android, where FILE is only accessible as opaque type and therefore fails to compile with incomplete type error.
Code now complies with: FIO38-C. Do not copy a FILE object, See: https://wiki.sei.cmu.edu/confluence/display/c/FIO38-C.+Do+not+copy+a+FILE+object

### CODE REVIEW

**Comment by Thecarisma** [comment]
FILE object is copied so a temporary FILE can be used for std output and input streams testing, and at the end of each test case the captured FILE object are reverted back to the original values. 
By disabling the FILE object copy testing involving assertions on the output streams will stop working.

The best approach I can think of now is to add a macro that will exclude the FILE capture feature during compilation and the flag to exclude the feature at runtime:

```c
CESTER_NO_STREAM_CAPTURING
--cester-nostreamcapture
```

**Comment by Thecarisma** [comment]
I will make an update to the framework to selectively compile FILE capturing feature

**Comment by Inkrementator** [comment]
Thanks, interesting. Why provide a runtime flag though?

**Comment by chenyulue** [comment]
[Issue 65](https://github.com/exoticlibraries/libcester/issues/65) may be an alternative solution to the error in Android.

**Comment by Thecarisma** [comment]
> Thanks, interesting. Why provide a runtime flag though?

I provide an alternate runtime flag, in in case the feature wants to exclude after the test has been compiled.

**Pull request closed without merging**
